In [37]:
import numpy as np

ar = np.array([[1,2,3],['a','b','c','d']])
print(ar, type(ar))
print(ar.ndim) #数组维数
print(ar.shape) # 2 x 3
print(ar.size) # 6 = 2x3
print(ar.dtype)
print(ar.itemsize)

[list([1, 2, 3]) list(['a', 'b', 'c', 'd'])] <class 'numpy.ndarray'>
1
(2,)
2
object
8


In [20]:
ar1 = np.array(range(10))
print(ar1)
ar2 = np.arange(10)
print(ar2)

ar3 = np.array(range(2,10))
print(ar3)
ar4 = np.arange(2,10)
print(ar4)

ar5 = np.array(range(1,10,2))
print(ar5)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6 7 8 9]
[2 3 4 5 6 7 8 9]
[1 3 5 7 9]


In [24]:
ar1 = np.linspace(2,10,num=5)
print(ar1)

[  2.   4.   6.   8.  10.]


In [36]:
ar1 = np.zeros(5)
print(ar1)
ar2 = np.zeros((3,))
print(ar2)
ar3 = np.zeros((3,2), dtype=int)
print(ar3)

[ 0.  0.  0.  0.  0.]
[ 0.  0.  0.]
[[0 0]
 [0 0]
 [0 0]]
