In [2]:
import numpy as np

ar = np.array([[1,2,3],['a','b','c','d']])
print(ar, type(ar))
print(ar.ndim) #数组维数
print(ar.shape) # 2 x 3
print(ar.size) # 6 = 2x3
print(ar.dtype)
print(ar.itemsize)

[list([1, 2, 3]) list(['a', 'b', 'c', 'd'])] <class 'numpy.ndarray'>
1
(2,)
2
object
8


In [3]:
ar1 = np.array(range(10))
print(ar1)
ar2 = np.arange(10)
print(ar2)

ar3 = np.array(range(2,10))
print(ar3)
ar4 = np.arange(2,10)
print(ar4)

ar5 = np.array(range(1,10,2))
print(ar5)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6 7 8 9]
[2 3 4 5 6 7 8 9]
[1 3 5 7 9]


In [4]:
ar1 = np.linspace(2,10,num=5)
print(ar1)

[  2.   4.   6.   8.  10.]


In [12]:
ar1 = np.zeros(5)
print(ar1)
ar2 = np.zeros((3,))
print(ar2)
ar3 = np.zeros((3,2), dtype=int)
print(ar3)
a4 = np.ones(3)
print(a4)
a5 = np.ones((2,3))
print(a5)

[ 0.  0.  0.  0.  0.]
[ 0.  0.  0.]
[[0 0]
 [0 0]
 [0 0]]
[ 1.  1.  1.]
[[ 1.  1.  1.]
 [ 1.  1.  1.]]


In [56]:
print(a5.T)

a1 = np.ones((2,5))
print(a1)
print(a1.reshape(5,2))
print('------\n')

a2 = np.reshape(np.array(range(12)), (3,4))
print(a2)

a3 = np.resize(np.array(range(16)),(4,4))
print(a3)

[[ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]]
[[ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]]
[[ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]]
------

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [27]:
ar1 = np.array(range(10), dtype=np.float)
print(ar1, ar1.dtype)
ar2 = ar1.astype(np.int32)
print(ar2, ar2.dtype)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.] float64
[0 1 2 3 4 5 6 7 8 9] int32


In [32]:
a = np.arange(5)
b = np.arange(5,9)
print(a, b)
ar1 = np.hstack((a,b))
print(ar1)

[0 1 2 3 4] [5 6 7 8]
[0 1 2 3 4 5 6 7 8]


In [37]:
a = np.array([[1],[2],[3]])
b = np.array([['a'],['b'],['c']])
print(a)
print(b)
ar1 = np.hstack((a,b))
print(ar1)


[[1]
 [2]
 [3]]
[['a']
 ['b']
 ['c']]
[['1' 'a']
 ['2' 'b']
 ['3' 'c']]


In [42]:
a = np.arange(5)
b = np.arange(5,10)
ar1 = np.vstack((a,b))
print(a, b)
print(ar1)
print(ar1.shape)

[0 1 2 3 4] [5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
(2, 5)


In [47]:
#如果a和b的长度不同，合并后变成一列
a = np.array([[1],[2],[3]])
b = np.array([['a'],['b'],['c'],['d']])
print(a)
print(b)
ar1 = np.vstack((a,b))
print(ar1)
print(ar1.shape)

[[1]
 [2]
 [3]]
[['a']
 ['b']
 ['c']
 ['d']]
[['1']
 ['2']
 ['3']
 ['a']
 ['b']
 ['c']
 ['d']]
(7, 1)


In [53]:
a = np.arange(5)
b = np.arange(5,10)
print(a,b)
# np.stack(arrays, axis=0)
ar1 = np.stack((a,b)) #默认是axis=0
print(ar1)
print(ar1.shape)
ar2 = np.stack((a,b), axis=1)
print(ar2)

[0 1 2 3 4] [5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
(2, 5)
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


In [79]:
ar = np.arange(16).reshape((4,4))
print(ar)
print('\n')
ar1 = np.hsplit(ar,2)
print(ar1)
print(type(ar1))
print('\n')
ar2 = np.vsplit(ar,4)
print(ar2)
print(type(ar2))
print('\n')


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]
<class 'list'>


[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]]), array([[12, 13, 14, 15]])]
<class 'list'>




In [38]:
ar = np.arange(6).reshape(2,3)
print(ar)
print('\n')
ar2 = ar
print(ar2 is ar)
ar1 = ar+10
print(ar1)
print(ar1 is ar)
print(ar*2)

ar3 = 1/ (ar+1)
print(ar3)

print(ar**0.5)

print(ar.min())
print(ar.max())
print(ar.sum())
print(ar.mean())
print(ar.var()) # 方差 = 各数据与平均值的差的平方，求和，再除以数据个数(n)
print(ar.std()) #标准差 = sqrt(方差)

print(np.sum(ar,axis=0))
print(np.sum(ar, axis = 1))

[[0 1 2]
 [3 4 5]]


True
[[10 11 12]
 [13 14 15]]
False
[[ 0  2  4]
 [ 6  8 10]]
[[ 1.          0.5         0.33333333]
 [ 0.25        0.2         0.16666667]]
[[ 0.          1.          1.41421356]
 [ 1.73205081  2.          2.23606798]]
0
5
15
2.5
2.91666666667
1.70782512766
[3 5 7]
[ 3 12]


In [47]:
ar = np.arange(16).reshape((4,4))
print(ar)

print(ar[2])
print(ar[1][2])
print(ar[1:3])
print(ar[2,2])
print(ar[1:3,1:3])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[ 8  9 10 11]
6
[[ 4  5  6  7]
 [ 8  9 10 11]]
10
[[ 5  6]
 [ 9 10]]


In [55]:
ar = np.arange(12).reshape((3,4))
i = np.array([True, False, True])
j = np.array([True, False, False, True])
print(ar)
print(i)
print(j)
print(ar[i])
print(ar[:,j])
ar2 = ar > 5
print(ar2)
print(ar[ar2])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ True False  True]
[ True False False  True]
[[ 0  1  2  3]
 [ 8  9 10 11]]
[[ 0  3]
 [ 4  7]
 [ 8 11]]
[[False False False False]
 [False False  True  True]
 [ True  True  True  True]]
[ 6  7  8  9 10 11]


In [70]:
a = np.random.rand()
print(a, type(a))
a = np.random.rand(5)
print(a)
a = np.random.rand(5,3)
print(a)

0.44070687213232496 <class 'float'>
[ 0.99107193  0.79287895  0.82253075  0.52489604  0.97956179]
[[ 0.77359095  0.84987714  0.97561876]
 [ 0.24075543  0.60797418  0.76541232]
 [ 0.24406519  0.41527731  0.91333412]
 [ 0.35310622  0.95642838  0.5399654 ]
 [ 0.107222    0.6152455   0.02030737]]
