In [2]:
import numpy as np
import pandas as pd

In [11]:
ar = np.random.rand(5)
print(ar)
s = pd.Series(ar)
print(s)
print(type(s))
print(s.index)
print(s.values, type(s.values))

[ 0.79603471  0.3458413   0.18513834  0.48551011  0.1235916 ]
0    0.796035
1    0.345841
2    0.185138
3    0.485510
4    0.123592
dtype: float64
<class 'pandas.core.series.Series'>
RangeIndex(start=0, stop=5, step=1)
[ 0.79603471  0.3458413   0.18513834  0.48551011  0.1235916 ] <class 'numpy.ndarray'>


In [13]:
dic = {'a':1, 'b':2, 'c':3}
s = pd.Series(dic)
print(s)

a    1
b    2
c    3
dtype: int64


In [20]:
ar = np.random.rand(10)
print(ar)
s = pd.Series(ar)
print(s)
s = pd.Series(ar, index=list('abcdefghij'))
print(s)

[ 0.27497181  0.20759129  0.42747388  0.22748759  0.18798213  0.63447497
  0.42584911  0.81500094  0.31914317  0.00447923]
0    0.274972
1    0.207591
2    0.427474
3    0.227488
4    0.187982
5    0.634475
6    0.425849
7    0.815001
8    0.319143
9    0.004479
dtype: float64
a    0.274972
b    0.207591
c    0.427474
d    0.227488
e    0.187982
f    0.634475
g    0.425849
h    0.815001
i    0.319143
j    0.004479
dtype: float64


In [22]:
s = pd.Series(10, index=range(4))
print(s)

0    10
1    10
2    10
3    10
dtype: int64


In [31]:
s = pd.Series(np.random.rand(5))
print(s)
print('-----')
print(s[1], type(s[1])) #索引
print(s[0:3])
print(s[::])
print(s[1:2])
print(s[2:-1])

0    0.971840
1    0.762705
2    0.583635
3    0.797500
4    0.270591
dtype: float64
-----
0.762705034896 <class 'numpy.float64'>
0    0.971840
1    0.762705
2    0.583635
dtype: float64
0    0.971840
1    0.762705
2    0.583635
3    0.797500
4    0.270591
dtype: float64
1    0.762705
dtype: float64
2    0.583635
3    0.797500
dtype: float64


In [36]:
s = pd.Series(np.random.rand(6), index = list('abcdef'))
print(s)
print(s['b'], type(s['b'])) #标签
print(s['b':'c'])

print('----')
print(s.reindex(list('dceafb')))
print(s.reindex(list('adfegg')))
print(s.reindex(list('adfegg'), fill_value=0))

a    0.569990
b    0.774204
c    0.733106
d    0.576168
e    0.271011
f    0.563963
dtype: float64
0.774203737622 <class 'numpy.float64'>
b    0.774204
c    0.733106
dtype: float64
----
d    0.576168
c    0.733106
e    0.271011
a    0.569990
f    0.563963
b    0.774204
dtype: float64
a    0.569990
d    0.576168
f    0.563963
e    0.271011
g         NaN
g         NaN
dtype: float64
a    0.569990
d    0.576168
f    0.563963
e    0.271011
g    0.000000
g    0.000000
dtype: float64


In [40]:
s1 = pd.Series(np.random.rand(4), index = ['Tom', 'Jack', 'Katte', 'Rose'])
s2 = pd.Series(np.random.rand(4), index = ['Marry', 'Wang', 'Katte', 'Rose'])
print(s1)
print(s2)
print('-----')
print(s1+s2) # 标签对其，空值和任何值计算结果仍为空值

Tom      0.850021
Jack     0.368426
Katte    0.676393
Rose     0.221380
dtype: float64
Marry    0.503561
Wang     0.037401
Katte    0.655854
Rose     0.518726
dtype: float64
-----
Jack          NaN
Katte    1.332247
Marry         NaN
Rose     0.740106
Tom           NaN
Wang          NaN
dtype: float64


In [49]:
# DataFrame
data = {
    'name':['Jack','Rose','Marry'],
    'age':[18,23,24],
    'gender':['male','female','female']
}
frame = pd.DataFrame(data)
print(frame, type(frame))
print(frame.index)
print(frame.columns)
print(frame.values)

   age  gender   name
0   18    male   Jack
1   23  female   Rose
2   24  female  Marry <class 'pandas.core.frame.DataFrame'>
RangeIndex(start=0, stop=3, step=1)
Index(['age', 'gender', 'name'], dtype='object')
[[18 'male' 'Jack']
 [23 'female' 'Rose']
 [24 'female' 'Marry']]


In [56]:
data = {'one':np.random.rand(3),
       'two':np.random.rand(3)} #个数必现相同
frame = pd.DataFrame(data)
print(frame)

data1 = {
    'a':[1,2,3],
    'b':[4,5,6],
    'c':[7,8,9]
}
#这里的key是column name
frame1 = pd.DataFrame(data1)
print(frame1)

df1 = pd.DataFrame(data1, columns=['a','b','d']) #重新制定column，实际上筛选出column是a和b的列，没有的d列值为Nan
print(df1)

df2 = pd.DataFrame(data1, index=['d','e','f'])
print(df2)

        one       two
0  0.298921  0.141359
1  0.280752  0.120983
2  0.112130  0.397396
   a  b  c
0  1  4  7
1  2  5  8
2  3  6  9
   a  b    d
0  1  4  NaN
1  2  5  NaN
2  3  6  NaN
   a  b  c
d  1  4  7
e  2  5  8
f  3  6  9


In [60]:
data = {
    'one':pd.Series(np.random.rand(2)),
    'two':pd.Series(np.random.rand(3)) #使用Series生成DataFrame可以不一样长
}
frame = pd.DataFrame(data)
print(frame)

data1 = {
    'one':pd.Series(np.random.rand(2), index=['a','b']),
    'two':pd.Series(np.random.rand(3), index=['a','b','c'])
}
frame1 = pd.DataFrame(data1)
print(frame1)

        one       two
0  0.083369  0.163361
1  0.442608  0.392231
2       NaN  0.803918
        one       two
a  0.335684  0.155025
b  0.383260  0.354414
c       NaN  0.461209


In [69]:
data = np.arange(12).reshape(3,4)
print(data)
frame = pd.DataFrame(data)
print(frame) #通过二维数据创建DataFrame
print('----')
frame1 = pd.DataFrame(data, columns=['a','b','c','d'], index=[2,3,4])
print(frame1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
   0  1   2   3
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11
----
   a  b   c   d
2  0  1   2   3
3  4  5   6   7
4  8  9  10  11


In [73]:
data = [{'a':1,'b':2},{'a':3,'b':4},{'a':5,'b':6,'c':7}]
print(data)
print('------')
frame = pd.DataFrame(data)
print(frame)

[{'a': 1, 'b': 2}, {'a': 3, 'b': 4}, {'a': 5, 'b': 6, 'c': 7}]
------
   a  b    c
0  1  2  NaN
1  3  4  NaN
2  5  6  7.0


In [76]:
data = {
    'Jack':{'math':90,'english':75,'art':89},
    'Mary':{'math':97,'english':88,'art':90},
    'Tom':{'english':89,'art':79}
}
print(data)
print('-----')
frame = pd.DataFrame(data)
print(frame)

{'Jack': {'math': 90, 'english': 75, 'art': 89}, 'Mary': {'math': 97, 'english': 88, 'art': 90}, 'Tom': {'english': 89, 'art': 79}}
-----
         Jack  Mary   Tom
art        89    90  79.0
english    75    88  89.0
math       90    97   NaN


In [108]:
df = pd.DataFrame(np.random.rand(12).reshape(3,4)*100, index = ['one','two','three'], columns=['a','b','c','d'])
print(df)
print('----')
data1 = df['a'] # 也等于df[['a']]
print(data1, type(data1))
data2 = df[['a','c']]
print(data2, type(data2))

print('----')
#选择行
data3 = df.loc['one']
print(data3, type(data3))
data4 = df.loc[['one','three']]
print(data4, type(data4))
print('-----#####')
print(df[0:1])
print(df[:-1])
print(df[::])
print('-----')

print(df.loc[['one','five']])
print(df.loc['one':'three'])

               a          b          c          d
one     4.501804  38.849194  81.447949   7.538959
two    54.537390  45.209564  69.856019  85.245189
three  17.136368  61.864907  90.524363  30.302834
----
one       4.501804
two      54.537390
three    17.136368
Name: a, dtype: float64 <class 'pandas.core.series.Series'>
               a          c
one     4.501804  81.447949
two    54.537390  69.856019
three  17.136368  90.524363 <class 'pandas.core.frame.DataFrame'>
----
a     4.501804
b    38.849194
c    81.447949
d     7.538959
Name: one, dtype: float64 <class 'pandas.core.series.Series'>
               a          b          c          d
one     4.501804  38.849194  81.447949   7.538959
three  17.136368  61.864907  90.524363  30.302834 <class 'pandas.core.frame.DataFrame'>
-----#####
            a          b          c         d
one  4.501804  38.849194  81.447949  7.538959
             a          b          c          d
one   4.501804  38.849194  81.447949   7.538959
two  54.537390

In [113]:
df = pd.DataFrame(np.random.rand(16).reshape(4,4)*100, index=['one','two','three','four'], columns=['a','b','c','d'])
print(df)
print('-----')
print(df.iloc[1], type(df.iloc[1]))
print(df.iloc[[0,2]])
print(df.iloc[[2,3,0]])

               a          b          c          d
one    44.972540  74.426512  68.443693   7.496914
two    43.612975  50.342302  91.155790  79.454513
three  91.264153  12.918690  95.054786  10.361407
four   78.307404  72.220684  53.144983  52.391569
-----
a    43.612975
b    50.342302
c    91.155790
d    79.454513
Name: two, dtype: float64 <class 'pandas.core.series.Series'>
               a          b          c          d
one    44.972540  74.426512  68.443693   7.496914
three  91.264153  12.918690  95.054786  10.361407
               a          b          c          d
three  91.264153  12.918690  95.054786  10.361407
four   78.307404  72.220684  53.144983  52.391569
one    44.972540  74.426512  68.443693   7.496914


In [119]:
df = pd.DataFrame(np.random.rand(16).reshape(4,4)*100, index=['one','two','three','four'], columns=['a','b','c','d'])
print(df)
print('-----')
b1 = df > 50
print(b1, type(b1))
print('---')
print(df[b1])
print('----')
b2 = df['a'] > 50
print(b2, type(b2))
print(df[b2])

               a          b          c          d
one    38.357518  14.336775  77.495786  59.608499
two    71.715963  95.854150  60.570773  61.811424
three  45.598723  25.203972  53.214939  53.012162
four   29.179138  50.641446   6.850252  66.394794
-----
           a      b      c     d
one    False  False   True  True
two     True   True   True  True
three  False  False   True  True
four   False   True  False  True <class 'pandas.core.frame.DataFrame'>
---
               a          b          c          d
one          NaN        NaN  77.495786  59.608499
two    71.715963  95.854150  60.570773  61.811424
three        NaN        NaN  53.214939  53.012162
four         NaN  50.641446        NaN  66.394794
----
one      False
two       True
three    False
four     False
Name: a, dtype: bool <class 'pandas.core.series.Series'>
             a         b          c          d
two  71.715963  95.85415  60.570773  61.811424


In [124]:
df = pd.DataFrame(np.random.rand(16).reshape(4,4)*100, index=['one','two','three','four'], columns=['a','b','c','d'])
print(df)
print('-----')
print(df['a'].loc[['one','three']])
print(df['a'].iloc[[2,3]])
print(df[0:3][['b','c']])

               a          b          c          d
one    71.956638  77.206273  90.668874  71.413711
two    51.370551  64.889110   0.760291  50.568108
three  47.968773  48.980438  83.153073  93.520700
four   10.350985  43.196065  40.234031  29.117191
-----
one      71.956638
three    47.968773
Name: a, dtype: float64
three    47.968773
four     10.350985
Name: a, dtype: float64
               b          c
one    77.206273  90.668874
two    64.889110   0.760291
three  48.980438  83.153073


In [127]:
df1 = pd.DataFrame(np.random.rand(16).reshape(4,4)*100,
                   columns = ['a','b','c','d'])
print(df1)
print('----')

print(df1.sort_values(['a'], ascending=True))


           a          b          c          d
0  97.331221  62.992248  71.606543  10.839071
1  97.819180  66.526151  54.853905  33.199865
2  14.844857  64.386233  61.694572  24.817305
3  53.475171  89.636712  79.745527  34.002976
----
           a          b          c          d
2  14.844857  64.386233  61.694572  24.817305
3  53.475171  89.636712  79.745527  34.002976
0  97.331221  62.992248  71.606543  10.839071
1  97.819180  66.526151  54.853905  33.199865
